CREATE TABLE IF NOT EXISTS token (
    id SERIAL PRIMARY KEY,
    token TEXT NOT NULL UNIQUE,
    id_usuario INTEGER NOT NULL REFERENCES usuario(id) ON DELETE CASCADE,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
