CREATE TABLE IF NOT EXISTS predicao (
    id SERIAL PRIMARY KEY,
    id_usuario INTEGER NULL REFERENCES usuario(id),
    guest_session_id UUID NULL,
    school VARCHAR(2) NOT NULL CHECK (school IN ('GP', 'MS')),
    sex VARCHAR(1) NOT NULL CHECK (sex IN ('F', 'M')),
    age INTEGER NOT NULL CHECK (age BETWEEN 15 AND 22),
    address VARCHAR(1) NOT NULL CHECK (address IN ('U', 'R')),
    famsize VARCHAR(3) NOT NULL CHECK (famsize IN ('LE3', 'GT3')),
    "Pstatus" VARCHAR(1) NOT NULL CHECK ("Pstatus" IN ('T', 'A')),
    "Medu" INTEGER NOT NULL CHECK ("Medu" BETWEEN 0 AND 4),
    "Fedu" INTEGER NOT NULL CHECK ("Fedu" BETWEEN 0 AND 4),
    "Mjob" VARCHAR(20) NOT NULL CHECK ("Mjob" IN ('teacher', 'health', 'services', 'at_home', 'other')),
    "Fjob" VARCHAR(20) NOT NULL CHECK ("Fjob" IN ('teacher', 'health', 'services', 'at_home', 'other')),
    reason VARCHAR(20) NOT NULL CHECK (reason IN ('home', 'reputation', 'course', 'other')),
    guardian VARCHAR(20) NOT NULL CHECK (guardian IN ('mother', 'father', 'other')),
    traveltime INTEGER NOT NULL CHECK (traveltime BETWEEN 1 AND 4),
    studytime INTEGER NOT NULL CHECK (studytime BETWEEN 1 AND 4),
    failures INTEGER NOT NULL CHECK (failures BETWEEN 0 AND 4),
    schoolsup VARCHAR(3) NOT NULL CHECK (schoolsup IN ('yes', 'no')),
    famsup VARCHAR(3) NOT NULL CHECK (famsup IN ('yes', 'no')),
    paid VARCHAR(3) NOT NULL CHECK (paid IN ('yes', 'no')),
    activities VARCHAR(3) NOT NULL CHECK (activities IN ('yes', 'no')),
    nursery VARCHAR(3) NOT NULL CHECK (nursery IN ('yes', 'no')),
    higher VARCHAR(3) NOT NULL CHECK (higher IN ('yes', 'no')),
    internet VARCHAR(3) NOT NULL CHECK (internet IN ('yes', 'no')),
    romantic VARCHAR(3) NOT NULL CHECK (romantic IN ('yes', 'no')),
    famrel INTEGER NOT NULL CHECK (famrel BETWEEN 1 AND 5),
    freetime INTEGER NOT NULL CHECK (freetime BETWEEN 1 AND 5),
    goout INTEGER NOT NULL CHECK (goout BETWEEN 1 AND 5),
    "Dalc" INTEGER NOT NULL CHECK ("Dalc" BETWEEN 1 AND 5),
    "Walc" INTEGER NOT NULL CHECK ("Walc" BETWEEN 1 AND 5),
    health INTEGER NOT NULL CHECK (health BETWEEN 1 AND 5),
    absences INTEGER NOT NULL CHECK (absences BETWEEN 0 AND 93),
    subject VARCHAR(20) NOT NULL CHECK (subject IN ('math', 'portuguese')),
    aprovado BOOLEAN NOT NULL,
    resultado_predicao JSONB NOT NULL,
    interpretacao_llm TEXT NULL,
    data_hora_criacao TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (id_usuario IS NOT NULL OR guest_session_id IS NOT NULL)
);
